### PR TITLE
fix: cache key stability

### LINKED ISSUE #140: cache key is unstable with additional cargo installs
If additional cargo installs happen after the cache step the calculation of cache key between restore and save is unstable due to it now including the registered package, as added by #138.

I'll work on a fix for this and put up a PR.

### PR DESCRIPTION
**Pull request by stevenh**
Ensure consistency of main and post configuration by storing and restoring it from state, which in turn ensures cache key stability.

Also:
* Fixed some typos.
* Use core.error for logging errors.
* Fix inverted condition on cache-all-crates.

Reverts: #138
Fixes #140

### CODE REVIEW

File: src/config.ts [hunk 1]
```diff
@@ -45,6 +46,15 @@ export class CacheConfig {
    */
   static async new(): Promise<CacheConfig> {
     const self = new CacheConfig();
+    const source = core.getState(STATE_CONFIG);
+    if (source !== "") {
+      // Post action, use what we calculated in the main action ensuring consistency.
+      Object.assign(self, JSON.parse(source));
+      self.workspaces = self.workspaces
+        .map((w: any) => new Workspace(w.root, w.target));
```
Comment (Swatinem) [inline src/config.ts:54]: Instead of this dance, I would rather make an explicit ser/deserialization step.

File: src/config.ts [hunk 2]
```diff
@@ -104,24 +114,13 @@ export class CacheConfig {
 
     self.keyEnvs = keyEnvs;
 
-    // Installed packages and their versions are also considered for the key.
-    const packages = await getPackages();
-    hasher.update(packages);
```
Comment (Swatinem) [inline src/config.ts:109]: I believe I understand what this whole problem is all about:

We used to consider all the `cargo install --list` (aka the `.cargo/bin` binaries) for the cache key. And running a `cargo install` as part of the workflow obviously changes that.

**Review by Swatinem — COMMENTED** [review]
lgtm, except the `Object.assign`/`JSON.parse` roundtrips. We should make it explicit what we are serializing, and deserialize things manually as well.

File: src/config.ts (hunk 2 above)
Comment (stevenh) [reply src/config.ts:109]: Correct, any changes via `cargo install` between the main action step (restore) and the post action step would change what's installed and hence re-calculating in post action step cause the key to change.

The original intent of that change was to allow it pin specific additional installs, but that's simply not possible without having distinct action steps, where the user has control over the items captured.

I considered various options but came to the conclusion that the solution proposed by @Boshen to use [taiki-e/install-action](https://github.com/taiki-e/install-action) to install a binary version of udeps instead of trying to get it caching properly was the best solution.

File: src/config.ts (hunk 1 above)
Comment (stevenh) [reply src/config.ts:54]: I think I known what you're looking for, will update.

**Comment by stevenh** [comment]
@Swatinem to make sure you didn't miss the notification 😃

**Review by Swatinem — APPROVED** [review]
lgtm, though the specifics of de/serialization can be improved later

**Comment by stevenh** [comment]
Thanks, appreciate your time.
