### PR TITLE
Only key by `Cargo.toml` and `Cargo.lock` files of workspace members

### LINKED ISSUE #179: Post job cleanup errors with "argument list too long" in repository with many `Cargo.toml`/`Cargo.lock` files
## Problem

I'm using `rust-cache` in a [repository](https://github.com/max-heller/mdbook-pandoc) with a large number of `Cargo.toml`/`Cargo.lock` files due to including [cargo](https://github.com/rust-lang/cargo) and the [rust book](https://github.com/rust-lang/book) as submodules (see e.g. [this subdirectory](https://github.com/rust-lang/book/tree/main/listings)):

<details>
<summary>Cargo.toml and Cargo.lock files</summary>

```
Lockfiles considered:
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/cargo/.cargo/config.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/cargo/benches/benchsuite/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/cargo/benches/capture/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/cargo/Cargo.lock
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/cargo/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/cargo/crates/cargo-platform/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/cargo/crates/cargo-test-macro/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/cargo/crates/cargo-test-support/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/cargo/crates/cargo-test-support/containers/apache/bar/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/cargo/crates/cargo-test-support/containers/sshd/bar/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/cargo/crates/cargo-util/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/cargo/crates/crates-io/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/cargo/crates/home/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/cargo/crates/mdman/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/cargo/crates/resolver-tests/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/cargo/crates/semver-check/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/cargo/crates/xtask-build-man/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/cargo/crates/xtask-bump-check/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/cargo/crates/xtask-stale-label/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/cargo/credential/cargo-credential-1password/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/cargo/credential/cargo-credential-libsecret/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/cargo/credential/cargo-credential-macos-keychain/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/cargo/credential/cargo-credential-wincred/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/cargo/credential/cargo-credential/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/cargo/tests/testsuite/cargo_add/add_basic/out/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/cargo/tests/testsuite/cargo_add/add_multiple/out/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-03/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-05/Cargo.lock
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-05/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-06/Cargo.lock
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-06/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-07/Cargo.lock
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-07/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-09/Cargo.lock
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-09/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-10/Cargo.lock
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-10/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-11/Cargo.lock
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-11/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-12/Cargo.lock
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-12/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-13/Cargo.lock
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-13/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-14/Cargo.lock
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-14/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-15/Cargo.lock
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-15/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-16/Cargo.lock
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-16/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-17/Cargo.lock
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-17/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-18/Cargo.lock
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-18/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-19/Cargo.lock
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-19/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-20/Cargo.lock
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-20/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-21/Cargo.lock
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-21/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-22/Cargo.lock
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-22/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-23/Cargo.lock
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-23/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-24/Cargo.lock
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-24/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-25/Cargo.lock
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/listing-20-25/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/no-listing-01-define-threadpool-struct/Cargo.lock
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/no-listing-01-define-threadpool-struct/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/no-listing-02-impl-threadpool-new/Cargo.lock
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/no-listing-02-impl-threadpool-new/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/no-listing-03-define-execute/Cargo.lock
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/no-listing-03-define-execute/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/no-listing-04-update-worker-definition/Cargo.lock
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/no-listing-04-update-worker-definition/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/no-listing-05-fix-worker-new/Cargo.lock
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/no-listing-05-fix-worker-new/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/no-listing-06-fix-threadpool-drop/Cargo.lock
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/no-listing-06-fix-threadpool-drop/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/no-listing-07-final-code/Cargo.lock
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/listings/ch20-web-server/no-listing-07-final-code/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-book/rust-toolchain
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-reference/style-check/Cargo.lock
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rust-reference/style-check/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rustc-dev-guide/ci/date-check/Cargo.lock
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/books/rustc-dev-guide/ci/date-check/Cargo.toml
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/Cargo.lock
    - /home/runner/work/mdbook-pandoc/mdbook-pandoc/Cargo.toml
```

</details>

These lockfiles aren't relevant to the compilation/caching of my project, since I only build the mdbook contained in each repository.

The number of lockfiles breaks the post-run cleanup script (it works fine without submodules cloned):

```
Post job cleanup.
Error: An error occurred trying to start process '/home/runner/runners/2.311.0/externals/node16/bin/node' with working directory '/home/runner/work/mdbook-pandoc/mdbook-pandoc'. Argument list too long
```

## Possible fixes

- Only consider lockfiles for workspace members instead of globbing for all lockfiles within a workspace. This would require parsing the workspace manifests to determine member crates
- Keep globbing for all lockfiles but pass them to the cleanup script in a way that doesn't result in the argument list too long error

### PR DESCRIPTION
**Pull request by max-heller**
Currently, we glob for all `Cargo.toml` and `Cargo.lock` files anywhere in a workspace, but this can pick up false positives (see #179). This PR switches to only using `Cargo.toml` files of workspace members (determined using [`cargo metadata --no-deps`](https://doc.rust-lang.org/cargo/commands/cargo-metadata.html#output-options)) and per-workspace `Cargo.lock` files.

Closes #179

### CODE REVIEW

File: src/config.ts [hunk 1]
```diff
@@ -189,7 +191,10 @@ export class CacheConfig {
         }
       }
 
-      const cargo_locks = sort_and_uniq(await globFiles(`${root}/**/Cargo.lock`));
+      const cargo_locks = sort_and_uniq(workspaceMembers
+        .map(member => path.join(member.path, "Cargo.lock"))
+        .filter(fs.existsSync)
+      );
```
Comment (Swatinem) [inline src/config.ts:197]: I’m wondering if this makes sense at all, since a workspace by definition only has one `Cargo.lock` file containing everything from all the members.

**Review by Swatinem — COMMENTED** [review]
this looks good, in theory.
however previously we had some problems with `cargo metadata` building everything within the workspace eagerly (on cache "restore"), which negated the whole purpose of the cache.

I’m wondering if the `--no-deps` flag might change that behavior or not, or if a more uptodate version of cargo does not suffer from this. But I am very reluctant to try and find out. Let me run a couple of tests for this, as the problem with `cargo metadata` was reproducible on https://github.com/getsentry/relay, and I can try with that on monday.

File: src/config.ts (hunk 1 above)
Comment (max-heller) [reply src/config.ts]: ah right, changed it to only check for a single `Cargo.lock` under each workspace root

**Comment by max-heller** [comment]
> however previously we had some problems with `cargo metadata` building everything within the workspace eagerly (on cache "restore"), which negated the whole purpose of the cache.
> 
> I’m wondering if the `--no-deps` flag might change that behavior or not

My guess is that it wouldn't be building anything, but downloading dependencies from the registry to analyze their manifests. The [documentation](https://doc.rust-lang.org/cargo/commands/cargo-metadata.html#output-options) for `--no-deps` says it "[doesn't] fetch dependencies", which sounds like what we want.

**Comment by max-heller** [comment]
> the problem with `cargo metadata` was reproducible on https://github.com/getsentry/relay, and I can try with that on monday

Did you get a chance to test this?

**Comment by Swatinem** [comment]
Sorry for the delay, I wasn’t able to reproduce the original problem with `cargo metadata` locally. Even back then it wasn’t so easy to reproduce I remember. Maybe in the meantime things might have changed. I will merge this and then do some tests in CI.
